apiVersion: apps/v1
kind: Deployment
metadata:
  name: finai-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finai
  template:
    metadata:
      labels:
        app: finai
    spec:
      containers:
        - name: finai
          image: ghcr.io/ronak-cn-98/fin.ai-3tier:912b367bafcea6f09bb34314a6c52a4f487512b1
          ports:
            - containerPort: 8080
          